application: moelydd #.appspot.com
version: A  # B
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt 
  
# Icons
- url: /ico/(.*) 
  static_files: static/ico/\1 
  upload: static/ico/(.*) 

# Images
- url: /img/(.*) 
  static_files: static/img/\1 
  upload: static/img/(.*) 

# Style Sheets
- url: /css/(.*) 
  static_files: static/css/\1 
  upload: static/css/(.*) 

# JavaScript
- url: /js/(.*) 
  static_files: static/js/\1 
  upload: static/js/(.*) 

# Fonts
- url: /fonts/(.*) 
  static_files: static/fonts/\1 
  upload: static/fonts/(.*) 

- url: .*
  script: main.wsgi_app
  